application: tweetqueue
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /util/update
  script: /controller.py
- url: /.*
  script: /controller.py
  login: admin
